dist: bionic
language: python
python:
- '3.6'
- '3.7'
- '3.8-dev'
before_install:
  - pip install -r requirements.txt
install:
- python setup.py test
script:
- pytest helloworld.py
- flake8 . --count --show-source --statistics
