dist: bionic
language: python
python:
- '3.6'
- '3.7'
services:
    - docker
before_install:
  - docker-compose -f web_server/docker-compose.yml up --build -d
  - pip install -r requirements.txt
script:
  - pytest tests/
  - flake8 . --count --show-source --statistics
